# Generated by Django 4.0.3 on 2022-04-08 16:54

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='artists',
            fields=[
                ('song', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('artist', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='users',
            fields=[
                ('username', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='songs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(choices=[('Pop', 'Pop'), ('Hip-Hop', 'Hip-Hop'), ('Classic', 'Classic'), ('Rock', 'Rock'), ('Country', 'Country')], max_length=60)),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musicapplication.artists')),
            ],
        ),
        migrations.CreateModel(
            name='ratings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveBigIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musicapplication.artists')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musicapplication.users')),
            ],
        ),
    ]
