# Generated by Django 4.0.2 on 2022-04-14 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapplication', '0003_songs_artist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songs',
            name='song',
            field=models.CharField(max_length=255),
        ),
    ]
