# Generated by Django 4.0.2 on 2022-04-14 05:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapplication', '0006_alter_songs_song'),
    ]

    operations = [
        migrations.AddField(
            model_name='songs',
            name='rating',
            field=models.PositiveBigIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
            preserve_default=False,
        ),
    ]
