# Generated by Django 4.0.2 on 2022-04-14 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicapplication', '0007_songs_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='songs',
            name='rating',
        ),
    ]
