# Generated by Django 4.0.2 on 2022-04-14 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapplication', '0008_remove_songs_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratings',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
