# Generated by Django 4.0.2 on 2022-04-15 04:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('musicapplication', '0009_alter_ratings_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratings',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='ratings',
            name='song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musicapplication.songs'),
        ),
        migrations.AlterField(
            model_name='songs',
            name='song',
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name='artists',
        ),
    ]
