# Generated by Django 4.0.2 on 2022-04-18 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapplication', '0013_song'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='song',
            name='song_artist',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
