# Generated by Django 4.0.2 on 2022-04-19 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicapplication', '0018_alter_rating_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='username',
        ),
        migrations.DeleteModel(
            name='user',
        ),
    ]
