# Generated by Django 4.0.2 on 2022-04-19 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapplication', '0019_remove_rating_username_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='genre',
            field=models.CharField(choices=[('Pop', 'Pop'), ('Hip-Hop', 'Hip-Hop'), ('Classic', 'Classic'), ('Rock', 'Rock'), ('Country', 'Country'), ('Indie', 'Indie'), ('EDM', 'EDM'), ('Jazz', 'Jazz'), ('RnB', 'RnB')], max_length=60),
        ),
    ]
